# Generated by Django 3.2.25 on 2024-04-21 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_auto_20240421_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('agents', models.ManyToManyField(related_name='team_agents', to=settings.AUTH_USER_MODEL, verbose_name='Leader')),
                ('commission_rules', models.ManyToManyField(to='users.CommissionRule', verbose_name='Commission Rules')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leader', to=settings.AUTH_USER_MODEL, verbose_name='Leader')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
