# Generated by Django 3.2.25 on 2024-04-22 07:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_alter_team_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinChanger',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('sar', models.FloatField(verbose_name='1 SAR equal to ? in EGP')),
                ('date', models.DateField(auto_now=True, unique=True, verbose_name='Changer Date')),
            ],
            options={
                'verbose_name': 'CoinChanger',
                'verbose_name_plural': 'CoinChangers',
            },
        ),
    ]
