# Generated by Django 3.2.25 on 2024-04-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0003_coinchanger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinchanger',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Changer Date'),
        ),
        migrations.AlterUniqueTogether(
            name='coinchanger',
            unique_together={('date',)},
        ),
    ]
