# Generated by Django 3.2.25 on 2024-04-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0004_auto_20240422_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinchanger',
            old_name='sar',
            new_name='egp_to_sar',
        ),
    ]
