# Generated by Django 3.2.25 on 2024-04-23 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_updatehistory_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commission', '0005_rename_sar_coinchanger_egp_to_sar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionRules',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('late_time', models.PositiveIntegerField(verbose_name='Late in Secounds')),
                ('deduction_days', models.PositiveIntegerField(verbose_name='Deduction in Days')),
                ('is_global', models.BooleanField(verbose_name='Set Global Rule')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department', verbose_name='')),
            ],
            options={
                'verbose_name': 'Deduction Rules',
                'verbose_name_plural': 'Deduction Rules',
            },
        ),
        migrations.CreateModel(
            name='TargetSlice',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('min_value', models.PositiveIntegerField(verbose_name='Min Value')),
                ('max_value', models.PositiveIntegerField(verbose_name='Max Value')),
                ('money', models.CharField(max_length=100, verbose_name='Commission')),
                ('is_money_percentage', models.BooleanField(verbose_name='Set Commession as Percentage')),
                ('is_global', models.BooleanField(verbose_name='Set Global Rule')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department', verbose_name='')),
            ],
            options={
                'verbose_name': 'Target Slice',
                'verbose_name_plural': 'Target Slices',
            },
        ),
        migrations.CreateModel(
            name='UserCommissionDetails',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('basic', models.BigIntegerField(null=True, verbose_name='Basic Salary')),
                ('set_deduction_rules', models.BooleanField(default=True, verbose_name='Set Deduction Rules')),
                ('set_global_commission_rules', models.BooleanField(default=True, verbose_name='Set Global Rule')),
                ('commission_rules', models.ManyToManyField(to='commission.TargetSlice', verbose_name='Commission Target Slices')),
                ('deduction_rules', models.ManyToManyField(to='commission.DeductionRules', verbose_name='Deduction Rules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='commission_rules',
            field=models.ManyToManyField(to='commission.TargetSlice', verbose_name='Commission Rules'),
        ),
    ]
