# Generated by Django 3.2.25 on 2024-04-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0006_auto_20240423_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommissiondetails',
            name='basic',
            field=models.PositiveIntegerField(default=0, verbose_name='Basic Salary'),
        ),
    ]
