# Generated by Django 3.2.25 on 2024-04-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0007_alter_usercommissiondetails_basic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinchanger',
            options={'verbose_name': 'Coin Changer', 'verbose_name_plural': 'Coin Changers'},
        ),
        migrations.AlterModelOptions(
            name='usercommissiondetails',
            options={'verbose_name': 'User Commission Details', 'verbose_name_plural': 'User Commission Details'},
        ),
    ]
