# Generated by Django 3.2.25 on 2024-04-25 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commission', '0008_auto_20240424_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='agents',
            field=models.ManyToManyField(related_name='team_agents', to=settings.AUTH_USER_MODEL, verbose_name='Agents'),
        ),
        migrations.AlterField(
            model_name='usercommissiondetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
