# Generated by Django 3.2.25 on 2024-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0009_auto_20240425_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductionrules',
            name='deduction_days',
            field=models.FloatField(verbose_name='Deduction in Days'),
        ),
    ]
