# Generated by Django 3.2.25 on 2024-04-30 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0010_alter_deductionrules_deduction_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommissiondetails',
            name='will_arrive_at',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Must Arrive At'),
        ),
        migrations.AddField(
            model_name='usercommissiondetails',
            name='will_leave_at',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Must Leave At'),
        ),
    ]
