# Generated by Django 3.2.25 on 2024-05-05 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_arrivingleaving_deuration_between'),
        ('commission', '0011_auto_20240430_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductionrules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='usercommissiondetails',
            name='deduction_rules',
            field=models.ManyToManyField(limit_choices_to={'is_global': False}, to='commission.DeductionRules', verbose_name='Deduction Rules'),
        ),
    ]
