# Generated by Django 3.2.25 on 2024-05-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0012_auto_20240505_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommissiondetails',
            name='deduction_rules',
            field=models.ManyToManyField(null=True, to='commission.DeductionRules', verbose_name='Deduction Rules'),
        ),
    ]
