# Generated by Django 3.2.25 on 2024-05-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0014_alter_usercommissiondetails_deduction_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommissiondetails',
            name='commission_rules',
            field=models.ManyToManyField(blank=True, to='commission.TargetSlice', verbose_name='Commission Target Slices'),
        ),
    ]
