# Generated by Django 3.2.25 on 2024-06-25 11:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0015_alter_usercommissiondetails_commission_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicRecord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('deduction_days', models.FloatField(verbose_name='Deduction Days')),
                ('deduction_money', models.IntegerField(verbose_name='Deduction Money')),
                ('kpi', models.FloatField(verbose_name='KPI')),
                ('gift', models.FloatField(verbose_name='Gift')),
                ('basic', models.FloatField(verbose_name='Taken Basic')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('user_commission_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commission.usercommissiondetails', verbose_name='User')),
            ],
            options={
                'unique_together': {('date', 'user_commission_details')},
            },
        ),
    ]
