# Generated by Django 3.2.25 on 2024-06-25 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0016_basicrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
