# Generated by Django 3.2.25 on 2024-06-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0017_alter_basicrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicrecord',
            name='basic',
            field=models.FloatField(default=0, verbose_name='Taken Basic'),
        ),
        migrations.AlterField(
            model_name='basicrecord',
            name='deduction_days',
            field=models.FloatField(default=0, verbose_name='Deduction Days'),
        ),
        migrations.AlterField(
            model_name='basicrecord',
            name='deduction_money',
            field=models.IntegerField(default=0, verbose_name='Deduction Money'),
        ),
        migrations.AlterField(
            model_name='basicrecord',
            name='gift',
            field=models.FloatField(default=0, verbose_name='Gift'),
        ),
        migrations.AlterField(
            model_name='basicrecord',
            name='kpi',
            field=models.FloatField(default=0, verbose_name='KPI'),
        ),
    ]
