# Generated by Django 3.2.25 on 2024-06-30 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0018_auto_20240626_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicrecord',
            name='user_commission_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commission.usercommissiondetails', verbose_name='User Commission Details'),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('commission_team', models.IntegerField(default=0, verbose_name='Commission From Team')),
                ('target', models.FloatField(default=0, verbose_name='Target')),
                ('gift', models.FloatField(default=0, verbose_name='Gift')),
                ('commission', models.FloatField(default=0, verbose_name='Commission')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('basic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commission.basicrecord', verbose_name='Basic')),
            ],
            options={
                'unique_together': {('date', 'basic')},
            },
        ),
    ]
