# Generated by Django 3.2.25 on 2024-07-01 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commission', '0019_auto_20240630_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicrecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='coinchanger',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Changer Date'),
        ),
        migrations.AlterUniqueTogether(
            name='basicrecord',
            unique_together={('date', 'user')},
        ),
        migrations.RemoveField(
            model_name='basicrecord',
            name='user_commission_details',
        ),
    ]
