# Generated by Django 3.2.25 on 2024-07-11 14:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_lead_date'),
        ('commission', '0020_auto_20240701_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('count', models.IntegerField(verbose_name='Subscriptions Count')),
                ('value', models.IntegerField(verbose_name='Money')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='targetslice',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='usercommissiondetails',
            name='commission_rules',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_global': False}, to='commission.TargetSlice', verbose_name='Commission Target Slices'),
        ),
        migrations.AlterField(
            model_name='usercommissiondetails',
            name='deduction_rules',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_global': False}, to='commission.DeductionRules', verbose_name='Deduction Rules'),
        ),
    ]
