# Generated by Django 3.2.25 on 2024-07-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0021_auto_20240711_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetslice',
            name='name',
            field=models.CharField(default='Name', max_length=150, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
