# Generated by Django 3.2.25 on 2024-07-15 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0022_targetslice_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('plus', models.IntegerField(verbose_name='Plus +2 Price')),
                ('american_leads', models.IntegerField(verbose_name='American Leads Price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='commission_team',
            new_name='target_Team',
        ),
    ]
