# Generated by Django 3.2.25 on 2024-07-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0023_auto_20240715_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='count',
            field=models.IntegerField(unique=True, verbose_name='Subscriptions Count'),
        ),
    ]
