# Generated by Django 3.2.25 on 2024-07-18 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commission', '0024_alter_subscription_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='american',
            field=models.FloatField(default=0, verbose_name='American Leads'),
        ),
        migrations.AddField(
            model_name='commission',
            name='american_count',
            field=models.IntegerField(default=0, verbose_name='American Leads Count'),
        ),
        migrations.AddField(
            model_name='commission',
            name='deduction',
            field=models.FloatField(default=0, verbose_name='Deduction'),
        ),
        migrations.AddField(
            model_name='commission',
            name='plus',
            field=models.FloatField(default=0, verbose_name='Plus +2'),
        ),
        migrations.AddField(
            model_name='commission',
            name='salary',
            field=models.FloatField(default=0, verbose_name='Total of Salary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commission',
            name='subscriptions',
            field=models.FloatField(default=0, verbose_name='Subscriptions'),
        ),
        migrations.AddField(
            model_name='commission',
            name='subscriptions_count',
            field=models.IntegerField(default=0, verbose_name='Subscriptions Count'),
        ),
        migrations.AddField(
            model_name='commission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='basic',
            field=models.FloatField(default=0, verbose_name='Basic'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='target_Team',
            field=models.FloatField(default=0, verbose_name='Target Team'),
        ),
        migrations.AlterUniqueTogether(
            name='commission',
            unique_together={('date', 'user')},
        ),
        migrations.RemoveField(
            model_name='commission',
            name='commission',
        ),
    ]
