# Generated by Django 3.2.25 on 2024-07-22 11:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0025_auto_20240718_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='basic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commission.basicrecord', verbose_name='Basic'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 22), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='salary',
            field=models.FloatField(default=0, verbose_name='Total of Salary'),
        ),
    ]
