# Generated by Django 3.2.25 on 2024-07-29 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0026_auto_20240722_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 29), verbose_name='Date'),
        ),
    ]
