# Generated by Django 3.2.25 on 2024-08-05 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0027_alter_commission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date',
            field=models.DateField(default=datetime.date(2024, 8, 5), verbose_name='Date'),
        ),
    ]
