# Generated by Django 3.2.25 on 2024-09-05 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0028_alter_commission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicrecord',
            name='take_annual',
            field=models.IntegerField(default=0, verbose_name='Take Annual'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 5), verbose_name='Date'),
        ),
    ]
