# Generated by Django 3.2.25 on 2024-09-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0029_alter_commission_date'),
        ('commission', '0029_auto_20240905_1020'),
    ]

    operations = [
    ]
