# Generated by Django 3.2.25 on 2024-09-05 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0030_merge_20240905_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 5), verbose_name='Date'),
        ),
    ]
