# Generated by Django 3.2.25 on 2024-09-25 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0035_alter_commission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 25), verbose_name='Date'),
        ),
    ]
