# Generated by Django 3.2.25 on 2024-10-29 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0038_alter_commission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date',
            field=models.DateField(default=datetime.date(2024, 10, 29), verbose_name='Date'),
        ),
    ]
