# Generated by Django 3.2.25 on 2024-12-08 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0039_alter_commission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmericanSubscription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('count', models.IntegerField(unique=True, verbose_name='American Subscriptions Count')),
                ('value', models.IntegerField(verbose_name='Money')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='american_subscriptions',
            field=models.FloatField(default=0, verbose_name='American Subscriptions'),
        ),
        migrations.AddField(
            model_name='commission',
            name='american_subscriptions_count',
            field=models.IntegerField(default=0, verbose_name='Amirecan Subscriptions Count'),
        ),
    ]
