# Generated by Django 3.2.25 on 2025-03-18 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0041_actionplan_deal_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
