# Generated by Django 3.2.25 on 2025-05-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_arrivingleaving_project'),
        ('commission', '0042_alter_actionplan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional',
            name='plus_10',
            field=models.IntegerField(default=100, verbose_name='Plus +10 Price'),
        ),
        migrations.AddField(
            model_name='basicrecord',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='commission',
            name='plus_10',
            field=models.FloatField(default=0, verbose_name='Plus +10'),
        ),
        migrations.AddField(
            model_name='commission',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='plus',
            field=models.IntegerField(default=50, verbose_name='Plus +5 Price'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='plus',
            field=models.FloatField(default=0, verbose_name='Plus +5'),
        ),
    ]
