# Generated by Django 3.2.25 on 2026-04-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0044_auto_20250827_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional',
            name='plus_15',
            field=models.IntegerField(default=150, verbose_name='Plus +15 Price'),
        ),
    ]
