# Generated by Django 3.2.25 on 2026-04-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0045_additional_plus_15'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='plus_15',
            field=models.FloatField(default=0, verbose_name='Plus +15'),
        ),
        migrations.AddField(
            model_name='commission',
            name='plus_15_count',
            field=models.IntegerField(default=0, verbose_name='Plus 15 Count'),
        ),
    ]
