# Generated by Django 3.2.25 on 2026-04-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0046_auto_20260426_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetslice',
            name='is_for_americans',
            field=models.BooleanField(default=False, verbose_name='Is For American Leads'),
        ),
    ]
