# Generated by Django 3.2.25 on 2026-07-02 06:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0047_targetslice_is_for_americans'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAmericanSubscription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('min_value', models.PositiveIntegerField(verbose_name='Min Value')),
                ('max_value', models.PositiveIntegerField(verbose_name='Max Value')),
                ('percentage', models.FloatField(verbose_name='Commission Percentage')),
            ],
            options={
                'verbose_name': 'American Subscription',
                'verbose_name_plural': 'American Subscriptions',
            },
        ),
    ]
