# Generated by Django 3.2.25 on 2026-09-30 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0048_salesamericansubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadersAmericanSubscription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('count', models.IntegerField(unique=True, verbose_name='Leaders American Subscriptions Count')),
                ('value', models.IntegerField(verbose_name='Money')),
            ],
            options={
                'verbose_name': 'Leaders American Subscription',
                'verbose_name_plural': 'Leaders American Subscriptions',
            },
        ),
    ]
