import type { FC } from 'react';

interface LoadingPageProps {}

const LoadingPage: FC<LoadingPageProps> = () => {
    return (
        <div className='fixed w-screen h-screen top-0 left-0 bg-[rgba(0,0,0,0.5)]  z-50 flex flex-col justify-center items-center'>
            <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 100 100"
                preserveAspectRatio="xMidYMid"
                width={205}
                height={205}
                style={{
                    shapeRendering: "auto",
                }}
                className='block bg-[transparent] ' 
                xmlnsXlink="http://www.w3.org/1999/xlink"
                >
                <g>
                    <circle
                    cx={50}
                    cy={50}
                    r={29}
                    strokeWidth={6}
                    stroke="#51c9c9"
                    strokeDasharray="45.553093477052 45.553093477052"
                    fill="none"
                    strokeLinecap="round"
                    >
                    <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="0.6493506493506493s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;360 50 50"
                    />
                    </circle>
                    <circle
                    cx={50}
                    cy={50}
                    r={18}
                    strokeWidth={6}
                    stroke="#51c9c9"
                    strokeDasharray="28.274333882308138 28.274333882308138"
                    strokeDashoffset="28.274333882308138"
                    fill="none"
                    strokeLinecap="round"
                    >
                    <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="0.6493506493506493s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;-360 50 50"
                    />
                    </circle>
                    <g />
                </g>
                {/* [ldio] generated by https://loading.io */}
                </svg>
            <h1 className='text-2xl text-[white]'>Loading ...</h1>
            
        </div>
    );
}

export default LoadingPage;
