# Generated by Django 3.2.25 on 2024-04-21 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_auto_20240421_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('name', models.CharField(max_length=100, verbose_name='Treasury Name')),
                ('owners', models.ManyToManyField(limit_choices_to={'role': 'OWNER'}, related_name='treasury_owners', to=settings.AUTH_USER_MODEL, verbose_name='Owners')),
                ('projects', models.ManyToManyField(related_name='treasury_owners', to='users.Project', verbose_name='Projects')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreasuryOutcome',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('details', models.CharField(max_length=250, verbose_name='Details')),
                ('creator', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.treasury', verbose_name='Treasury')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreasuryIncome',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('details', models.CharField(max_length=250, verbose_name='Details')),
                ('creator', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.treasury', verbose_name='Treasury')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
