# Generated by Django 3.2.25 on 2024-04-21 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treasury',
            options={'verbose_name': 'Treasury', 'verbose_name_plural': 'Treasuries'},
        ),
        migrations.RemoveField(
            model_name='treasuryincome',
            name='creator',
        ),
        migrations.AddField(
            model_name='treasuryincome',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.RemoveField(
            model_name='treasuryoutcome',
            name='creator',
        ),
        migrations.AddField(
            model_name='treasuryoutcome',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
