# Generated by Django 3.2.25 on 2024-04-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_auto_20240421_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasuryincome',
            name='treasury',
        ),
        migrations.RemoveField(
            model_name='treasuryoutcome',
            name='treasury',
        ),
        migrations.DeleteModel(
            name='Treasury',
        ),
    ]
