# Generated by Django 3.2.25 on 2024-04-25 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treasury', '0004_auto_20240423_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('creator', models.ForeignKey(limit_choices_to={'role': 'OWNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('user', models.ForeignKey(limit_choices_to={'role__in': ['AGENT', 'MANAGER', 'HR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_taker', to=settings.AUTH_USER_MODEL, verbose_name='Taker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
