# Generated by Django 3.2.25 on 2024-05-13 14:43

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treasury', '0005_advance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('message', models.CharField(max_length=250, verbose_name='Message')),
                ('for_users', models.ManyToManyField(related_name='for_users', to=settings.AUTH_USER_MODEL, verbose_name='For Users')),
                ('seen_by_users', models.ManyToManyField(related_name='seen_by_users', to=settings.AUTH_USER_MODEL, verbose_name='Seen by Users')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
