# Generated by Django 3.2.25 on 2024-05-13 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treasury', '0007_notification_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='seen_by_users',
            field=models.ManyToManyField(blank=True, related_name='seen_by_users', to=settings.AUTH_USER_MODEL, verbose_name='Seen by Users'),
        ),
    ]
