# Generated by Django 3.2.25 on 2024-05-14 09:01

from django.db import migrations, models
import treasury.models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0008_alter_notification_seen_by_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deadline',
            field=models.DateTimeField(default=treasury.models.tomorrow, verbose_name='Deadline'),
        ),
    ]
