# Generated by Django 3.2.25 on 2024-06-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0009_notification_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryoutcome',
            name='from_advance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treasury.advance', verbose_name='Advance'),
        ),
    ]
