# Generated by Django 3.2.25 on 2024-06-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0018_auto_20240626_1044'),
        ('treasury', '0010_treasuryoutcome_from_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryoutcome',
            name='from_basic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commission.basicrecord', verbose_name='Basic'),
        ),
    ]
