# Generated by Django 3.2.25 on 2024-07-29 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0027_alter_commission_date'),
        ('treasury', '0011_treasuryoutcome_from_basic'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryoutcome',
            name='from_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commission.commission', verbose_name='Salary'),
        ),
    ]
