# Generated by Django 3.2.25 on 2024-09-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0012_treasuryoutcome_from_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50, verbose_name='Advance Status'),
        ),
    ]
