# Generated by Django 3.2.25 on 2024-12-05 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_genericfilter_get_queryset_text'),
        ('treasury', '0013_advance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryoutcome',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.project', verbose_name='project'),
        ),
    ]
