# Generated by Django 3.2.25 on 2024-12-09 13:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_genericfilter_get_queryset_text'),
        ('treasury', '0015_alter_treasuryoutcome_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasuryoutcome',
            name='project',
        ),
        migrations.CreateModel(
            name='ProjectsGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('projects', models.ManyToManyField(to='users.Project', verbose_name='Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='treasuryoutcome',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.projectsgroup', verbose_name='Project Group'),
        ),
    ]
