# Generated by Django 3.2.25 on 2024-12-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0016_auto_20241209_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryincome',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='treasuryoutcome',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
