# Generated by Django 3.2.25 on 2024-03-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='basic',
            field=models.BigIntegerField(null=True, verbose_name='Basic Salary'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(default='Agent', max_length=100, verbose_name='Title'),
        ),
    ]
