# Generated by Django 3.2.25 on 2024-03-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240313_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deduction_rules',
            field=models.BooleanField(default=True, verbose_name='Set Deduction Rules'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.project', verbose_name='Project'),
        ),
    ]
