# Generated by Django 3.2.25 on 2024-04-17 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240317_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=250, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='project',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=250, verbose_name='UUID'),
        ),
    ]
