# Generated by Django 3.2.25 on 2024-04-18 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models_utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240417_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('picture', models.ImageField(upload_to=utils.models_utils.image_upload_path, verbose_name='Profile Picture')),
                ('telegram_id', models.PositiveIntegerField(null=True, verbose_name='Telegram ID')),
                ('about', models.TextField(blank=True, verbose_name='About Text')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('phone', models.CharField(max_length=13, validators=[utils.models_utils.validate_lead_number], verbose_name='Phone Number')),
                ('name', models.CharField(max_length=100, verbose_name='Lead Name')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Day Date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='ArrivingLeaving',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Day Date')),
                ('arriving_at', models.DateTimeField(auto_now_add=True, verbose_name='Arrining Date & Time')),
                ('leaving_at', models.DateTimeField(auto_now_add=True, verbose_name='Leaving Date & Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('date', 'user')},
            },
        ),
    ]
