# Generated by Django 3.2.25 on 2024-04-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_lead_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateField(null=True, verbose_name='Day Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('MANAGER', 'Manager'), ('OWNER', 'Owner')], default='AGENT', max_length=100, null=True, verbose_name='Role'),
        ),
    ]
