# Generated by Django 3.2.25 on 2024-04-21 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240418_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('min_lead_count', models.PositiveIntegerField(verbose_name='Min Leads Count')),
                ('max_lead_count', models.PositiveIntegerField(verbose_name='Max Leads Count')),
                ('commission', models.PositiveIntegerField(verbose_name='Commission')),
                ('is_global', models.BooleanField(verbose_name='Set Global Rule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeductionRules',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('late_time', models.PositiveIntegerField(verbose_name='Late in Secounds')),
                ('deduction_in_days', models.PositiveIntegerField(verbose_name='Deduction in Days')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='deduction_rules',
            new_name='set_deduction_rules',
        ),
        migrations.AddField(
            model_name='user',
            name='set_global_commission_rules',
            field=models.BooleanField(default=True, verbose_name='Set Global Rule'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_commission_rules',
            field=models.ManyToManyField(to='users.CommissionRule', verbose_name='Custom Commission Rules'),
        ),
    ]
