# Generated by Django 3.2.25 on 2024-04-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20240421_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deductionrules',
            options={'verbose_name': 'Deduction Rules', 'verbose_name_plural': 'Deduction Rules'},
        ),
    ]
