# Generated by Django 3.2.25 on 2024-04-21 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20240421_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('previous_values', models.TextField()),
                ('model_name', models.CharField(max_length=100)),
                ('model_uuid', models.UUIDField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Update History',
                'verbose_name_plural': 'Update Histories',
            },
        ),
    ]
