# Generated by Django 3.2.25 on 2024-04-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_updatehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatehistory',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated At'),
        ),
    ]
