# Generated by Django 3.2.25 on 2024-04-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0006_auto_20240423_1043'),
        ('users', '0016_alter_updatehistory_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeductionRules',
        ),
        migrations.AlterModelOptions(
            name='arrivingleaving',
            options={'verbose_name': 'Arriving Leaving', 'verbose_name_plural': 'Arriving Leaving'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='custom_commission_rules',
        ),
        migrations.RemoveField(
            model_name='user',
            name='set_deduction_rules',
        ),
        migrations.RemoveField(
            model_name='user',
            name='set_global_commission_rules',
        ),
        migrations.DeleteModel(
            name='CommissionRule',
        ),
    ]
