# Generated by Django 3.2.25 on 2024-04-24 10:44

from django.db import migrations, models
import utils.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20240423_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('MANAGER', 'Manager'), ('OWNER', 'Owner')], default='AGENT', max_length=100, validators=[utils.models_utils.validate_role], verbose_name='Role'),
        ),
    ]
