# Generated by Django 3.2.25 on 2024-04-24 12:22

from django.db import migrations, models
import utils.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivingleaving',
            name='leaving_at',
            field=models.DateTimeField(null=True, verbose_name='Leaving Date & Time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('MANAGER', 'Manager'), ('OWNER', 'Owner'), ('HR', 'HR')], default='AGENT', max_length=100, validators=[utils.models_utils.validate_role], verbose_name='Role'),
        ),
    ]
