# Generated by Django 3.2.25 on 2024-04-25 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models_utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20240424_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11, null=True, validators=[utils.models_utils.validate_user_number], verbose_name='Phone Number'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('details', models.TextField(max_length=100, verbose_name='Details')),
                ('type', models.CharField(choices=[('GLOBAL', 'Global'), ('ANNUAL', 'Annual'), ('VACATION', 'Vacation'), ('LATE', 'Late')], default='GLOBAL', max_length=50, verbose_name='Request Type')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department', verbose_name='Department')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
