# Generated by Django 3.2.25 on 2024-04-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20240425_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ANNUAL', 'Accepted'), ('VACATION', 'Rejected')], default='PENDING', max_length=50, verbose_name='Request Status'),
        ),
    ]
