# Generated by Django 3.2.25 on 2024-04-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
