# Generated by Django 3.2.25 on 2024-04-29 10:47

from django.db import migrations, models
import utils.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_profile_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=utils.models_utils.image_upload_path, verbose_name='Profile Picture'),
        ),
    ]
