# Generated by Django 3.2.25 on 2024-04-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivingleaving',
            name='deuration_between',
            field=models.PositiveIntegerField(null=True, verbose_name='Late in secounds'),
        ),
    ]
