# Generated by Django 3.2.25 on 2024-04-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_arrivingleaving_deuration_between'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivingleaving',
            name='deuration_between',
            field=models.PositiveIntegerField(null=True, verbose_name='Deuration in secounds'),
        ),
    ]
