# Generated by Django 3.2.25 on 2024-05-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_arrivingleaving_deuration_between'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrivingleaving',
            name='deuration_between',
        ),
    ]
