# Generated by Django 3.2.25 on 2024-05-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_arrivingleaving_deuration_between'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='note',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50, verbose_name='Request Status'),
        ),
    ]
