# Generated by Django 3.2.25 on 2024-06-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_fingerprintid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprintid',
            name='name',
            field=models.CharField(default='PC', max_length=100, verbose_name='Name'),
        ),
    ]
