# Generated by Django 3.2.25 on 2024-06-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_fingerprintid_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(null=True, verbose_name='Date of Request'),
        ),
    ]
