# Generated by Django 3.2.25 on 2024-06-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='details',
            field=models.TextField(max_length=300, verbose_name='Details'),
        ),
    ]
