# Generated by Django 3.2.25 on 2024-07-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_request_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crm_username',
            field=models.CharField(blank=True, max_length=200, verbose_name='CRM Username'),
        ),
    ]
