# Generated by Django 3.2.25 on 2024-07-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_user_crm_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Day Date'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
    ]
