# Generated by Django 3.2.25 on 2024-07-09 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20240708_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Day Date'),
        ),
    ]
