# Generated by Django 3.2.25 on 2024-07-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_lead_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_password',
            new_name='password_normal',
        ),
    ]
