# Generated by Django 3.2.25 on 2024-09-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_rename__password_user_password_normal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annual_count',
            field=models.IntegerField(default=0, verbose_name='Annual Count'),
        ),
    ]
