# Generated by Django 3.2.25 on 2024-08-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_rename__password_user_password_normal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintid',
            name='unique_id',
            field=models.CharField(max_length=100, verbose_name='Unique ID'),
        ),
    ]
