# Generated by Django 3.2.25 on 2024-09-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_fingerprintid_unique_id'),
        ('users', '0036_user_annual_count'),
    ]

    operations = [
    ]
