# Generated by Django 3.2.25 on 2024-09-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_merge_20240905_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fp_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Figner Print ID'),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('DEPARTURE', 'Departure'), ('VACATION', 'Vacation'), ('LATE', 'Late')], default='GLOBAL', max_length=50, verbose_name='Request Type'),
        ),
    ]
