# Generated by Django 3.2.25 on 2024-09-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20240916_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivingleaving',
            name='arriving_at',
            field=models.DateTimeField(verbose_name='Arrining Date & Time'),
        ),
        migrations.AlterField(
            model_name='arrivingleaving',
            name='date',
            field=models.DateField(verbose_name='Day Date'),
        ),
    ]
