# Generated by Django 3.2.25 on 2024-09-19 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20240916_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZKConfig',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('ip', models.CharField(max_length=20, unique=True, verbose_name='IP Address')),
                ('port', models.PositiveBigIntegerField(verbose_name='Port')),
                ('timeout', models.PositiveIntegerField(verbose_name='Connection Timeout')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('force_udp', models.BooleanField(verbose_name='Force UDP')),
                ('ommit_ping', models.BooleanField(verbose_name='Ommit Ping')),
                ('is_default', models.BooleanField(verbose_name='Set Default')),
                ('last_uid', models.PositiveBigIntegerField(verbose_name='Last Machine UID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
