# Generated by Django 3.2.25 on 2024-09-25 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_zkconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('date', models.DateField(null=True, verbose_name='Date of Record')),
                ('json_data', models.TextField(max_length=2000, verbose_name='Data as Serialized Json')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
