# Generated by Django 3.2.25 on 2024-10-13 12:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_reportrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
