# Generated by Django 3.2.25 on 2024-12-03 12:53

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0042_project_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Page name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubPage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Page name')),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mainpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('main_pages', models.ManyToManyField(blank=True, to='users.MainPage', verbose_name='main_pages')),
                ('permissions', models.ManyToManyField(blank=True, related_name='group_permissions', to='auth.Permission', verbose_name='permissions')),
                ('sub_pages', models.ManyToManyField(blank=True, to='users.SubPage', verbose_name='sub_pages')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='custom_groups',
            field=models.ManyToManyField(blank=True, help_text='\n            The groups this user belongs to. A user will get all permissions \n            granted to each of their groups.\n        ', related_name='user_groups_set', related_query_name='user_groups', to='users.Group', verbose_name='groups'),
        ),
    ]
