# Generated by Django 3.2.25 on 2024-12-05 09:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0043_auto_20241203_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericFilter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date & Time')),
                ('get_queryset_text', models.CharField(max_length=150, verbose_name='Filter param')),
                ('layer_index', models.PositiveIntegerField(default=0, verbose_name='layer of index')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('groups', models.ManyToManyField(blank=True, help_text='\n            The groups this user belongs to. A user will get all permissions \n            granted to each of their groups.\n        ', related_name='filter_groups_set', related_query_name='filter_groups', to='users.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
