# Generated by Django 3.2.25 on 2024-12-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_genericfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericfilter',
            name='get_queryset_text',
            field=models.TextField(max_length=2000, verbose_name='Filter param'),
        ),
    ]
