# Generated by Django 3.2.25 on 2024-12-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_genericfilter_get_queryset_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericfilter',
            name='get_queryset_text',
            field=models.TextField(max_length=2000, verbose_name='Filter execute code context (user,queryset)'),
        ),
    ]
