# Generated by Django 3.2.25 on 2025-05-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_genericfilter_get_queryset_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivingleaving',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.project', verbose_name='Project'),
        ),
    ]
