# Generated by Django 3.2.25 on 2025-08-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_whatsappaccount_whatsappnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.project', verbose_name='Project'),
        ),
    ]
