# Generated by Django 3.2.25 on 2026-04-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_lead_unique_project_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='market',
            field=models.CharField(blank=True, choices=[('SAUDI', 'Saudi'), ('AMERICAN', 'American'), ('AMERICAN_AND_SAUDI', 'American and Saudi')], max_length=50, null=True, verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Source'),
        ),
    ]
